options:
  bcf_controller_ip:
    type: string
    default: ""
    description: "BCF Controller IP"
  bcf_controller_port:
    type: int
    default: 8000
    description: "BCF Controller Port"
  bcf_controller_username:
    type: string
    default: ""
    description: "BCF Controller username"
  bcf_controller_password:
    type: string
    default: ""
    description: "BCF Controller password"
  ssh_username:
    type: string
    default: "ubuntu"
    description: "SSH Username for remote nodes"
  ssh_password:
    type: string
    default: ""
    description: "SSH Password for remote nodes"
  debug:
    type: boolean
    default: False
    description: "Output extended logging information"
  network_vlan_ranges:
    type: string
    default: "physnet1:100:3000"
    description: "Comma separated list of physical network vlans"
  phy_int_bridge:
    type: string
    default: "physnet1:br-eth0"
    description: "OVS bridge that will contain the bond interface"
  bridge_mappings:
    type: string
    default: "physnet1:br-eth0"
    description: "Mappings between physical networks and ovs bridges"
  bond_interfaces:
    type: string
    default: "eth1,eth2"
    description: "Comma separated list of interfaces to configure"
